type SocialType =
  'INSTAGRAM'
  | 'FACEBOOK'
  | 'YOUTUBE'
  | 'TIKTOK'
  | 'LINKEDIN'
  | 'TWITCH'
  | 'TWITTER'
  | 'TELEGRAM'
  | 'BEHANCE'
  | 'AMAZON'
  | 'SPOTIFY'
  | 'CODEPEN'
  | 'DISCORD'
  | 'GITHUB'
  | 'GITLAB'
  | 'FREECODECAMP'
  | 'MEDIUM'
  | 'DEVIANTART'
  | 'REDDIT'
  | 'SLACK'
  | 'SOUNDCLOUD'
  | 'SKYPE'
  | 'STEAM'
  | 'TUMBLR'
  | 'WHATSAPP'
  | 'OTHER'

export default SocialType